#pragma once

#include <optional>
#include <raylib.h>

#include "planet_visual.hpp"
#include "utils.hpp"
#include "vectors.hpp"

struct CelestialBodyInit {
    str name;
    const Vec3& position;
    const Vec3& velocity;
    double gravitational_mass;
    float radius_2d;
    float radius_3d;
    const std::optional<Color>& color;
    double orbital_period_seconds;
    const std::optional<str>& texture_path = std::nullopt;
    double j2 = 0.0;
    double equatorial_radius = 0.0;
    const Vec3& pole_axis = {};
};

template<std::size_t NUM_CELESTIAL_BODIES>
struct CelestialBodies {
    // Position
    alignas(16) double pos_x[NUM_CELESTIAL_BODIES]{};
    alignas(16) double pos_y[NUM_CELESTIAL_BODIES]{};
    alignas(16) double pos_z[NUM_CELESTIAL_BODIES]{};

    // Velocity
    alignas(16) double vel_x[NUM_CELESTIAL_BODIES]{};
    alignas(16) double vel_y[NUM_CELESTIAL_BODIES]{};
    alignas(16) double vel_z[NUM_CELESTIAL_BODIES]{};

    bool enabled[NUM_CELESTIAL_BODIES]{};

    double original_gravitational_masses[NUM_CELESTIAL_BODIES]{}; // immutable GM
    double gravitational_masses[NUM_CELESTIAL_BODIES]{}; // effective GM; combined system GM in planet-systems mode
    str names[NUM_CELESTIAL_BODIES]{};

    float draw_radii_2d[NUM_CELESTIAL_BODIES]{};
    float draw_radii_3d[NUM_CELESTIAL_BODIES]{};
    std::optional<Color> colors[NUM_CELESTIAL_BODIES]{};

    // Approximate orbital period (parent-relative for moons, heliocentric for planets;
    // the Sun uses Pluto's period so its history — which bounds how far back center-relative
    // trails can reach — spans every other body's full tail)
    // Rendering-only; sets the orbit-trail sampling cadence and tail length
    double orbital_period_seconds[NUM_CELESTIAL_BODIES]{};

    PlanetVisual planet_visuals[NUM_CELESTIAL_BODIES]{};

    // Oblateness (zonal J2) parameters. 0 -> spherical point masses (ex. sun, moons, Pluto)
    // set for oblate planets so their satellites feel the equatorial-bulge perturbation.
    double j2[NUM_CELESTIAL_BODIES]{}; // dimensionless second zonal harmonic
    double equatorial_radii[NUM_CELESTIAL_BODIES]{}; // meters, reference radius for the J2 term
    Vec3 pole_axes[NUM_CELESTIAL_BODIES]{}; // unit spin axis in the simulation's J2000 ecliptic frame

    explicit CelestialBodies(std::array<CelestialBodyInit, NUM_CELESTIAL_BODIES> bodies);

    [[nodiscard]] Vec3 position(std::size_t i) const;
    [[nodiscard]] Vec3 velocity(std::size_t i) const;

    void set_position(std::size_t i, const Vec3& position);
    void set_velocity(std::size_t i, const Vec3& velocity);

    [[nodiscard]] double distance_to(std::size_t i, std::size_t to) const;

    [[nodiscard]] double get_mass(std::size_t i) const;

    // J2 acceleration generated by this body at a target point
    // The direction must be a unit vector from this body's center to the target.
    [[nodiscard]] Vec3 j2_acceleration_at(
        std::size_t i,
        const Vec3& source_to_target_direction,
        double distance
    ) const;

    [[nodiscard]] Vec3 acceleration_due_to(std::size_t i, std::size_t source) const;
};
